server:
  hostname: 127.0.0.1
  port: 3000
database:
  type: mariadb
  host: 127.0.0.1
  port: 3306
  username: username
  password: password
  database: database
  logging: false
redis: redis://127.0.0.1:6379
sessionSecret: Don't leak this
